base:
  project: cat-dog-classification
  random_state: 42
  target_col: target

data_source:
  s3_source_cat: data_given/cat
  s3_source_dog: data_given/dog

load_data:
  raw_dataset_csv: data/raw/pets.csv

split_data:
  train_path: data/processed/train_pets.csv
  test_path: data/processed/test_pets.csv
  test_size: 0.2

  
reports:
  params: report/params.json
  scores: report/scores.json

model_dir: saved_models

webapp_model_dir: prediction_service/model/model.joblib
